# Site settings
title: Kontinu
email: jmarcos.cano@gmail.com
url: "/"
baseurl: home
description: "Kontinu Guatemala - Consultoria Devops en Guatemala, nos especializamos en: Cloud, Docker, SCRUM, Continuous Delivery, Continuous Integration"
keywords: "consultoria devops,devops,consultoria,cd,ci,continuous,docker,devopsguatemala"
skills: "Devops Consulting"
meta_author: Cano Marcos

# Google webmaster tools
google_verify:


# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:


# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-111567273-1


## google optimize
go:
  # id:

# Contact form:
#- static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
# 1:
# salmon - azul - azulgris
# e49695  003366 263340
color:
  primary: FF7E79 #80B3FF
  primary-rgb: "255,242,241" #"128,179,255"
  secondary: 1d4063 #FD6E8A
  secondary-dark: 243342 #A2122F


about:
  column1: Somos una empresa que nos dedicamos a iniciar, orientar y a que nuestros clientes adopten todas las buenas practicas que los dirigir谩n hacia la transformaci贸n DevOps; Devops es la combinaci贸n de filosof铆as culturales, nuevas practicas y uso de herramientas entre equipos multi-funcionales que permiten incrementar la habilidad de la organizaci贸n para la entrega de software a altas velocidades.
  column2: Logramos que nuestros clientes adopten Devops mediante capacitaciones, talleres, pruebas de diagn贸stico y entrenamiento del personal, para que as铆 puedan cumplir con la alta demanda y tengan una mejor ventaja competitiva en la industria de tecnolog铆a.



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  - title: bitbucket
    url: http://gitlab.com/kontinu/home
  - title: github
    url: http://github.com/kontinu/home



# Postal address (add as many lines as necessary)
address:
  - line:   Guatemala City.
  - line:   +(502) 30093002


# Footer settings
footer:
  copyright: Kontinu
  location: Ubicaci贸n
  social: En la Web
  credits: Cr茅ditos
# Credits content
credits: 'Kontinu 2017 using Jekyll free-lancer theme'



# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap